"""Generate schemas.zig: input schemas for zmcp-computer's tools.

Sources (both read-only):
  * computer_control_mcp 0.3.10: FastMCP `list_tools()` dumped to cc_tools.json
    (see the zmcp-computer README for the dump recipe).
  * clawdcursor 0.9.3: schema.snapshot.json + src/tools/compact.ts, merged the
    way compact.ts buildCompoundSchema() does (first delegate wins, enums are
    unioned, only `action` is required).

Usage: python gen_schemas.py <cc_tools.json> <clawdcursor checkout> > schemas.zig
"""
import json
import re
import sys

cc_path, clawd = sys.argv[1], sys.argv[2]
cc = json.load(open(cc_path, encoding='utf8'))
src = open(clawd + '/src/tools/compact.ts', encoding='utf8').read()
snap = {t['name']: t for t in json.load(open(clawd + '/schema.snapshot.json', encoding='utf8'))['tools']}


def routes(name):
    body = re.search(r'const %s: ActionRoute\[\] = \[(.*?)\n\];' % name, src, re.S).group(1)
    out = []
    for m in re.finditer(r"\{\s*action:\s*'([^']+)',\s*delegate:\s*'([^']+)'(?:,\s*argRemap:\s*\{([^}]*)\})?", body):
        remap = dict(re.findall(r"(\w+):\s*'(\w+)'", m.group(3) or ''))
        out.append((m.group(1), m.group(2), remap))
    return out


def compound(rs, extra=None):
    props = {"action": {"type": "string", "enum": [a for a, _, _ in rs],
                        "description": "Which sub-action to perform. See this tool's description for the enum of valid values."}}
    for a, d, remap in rs:
        for pname, pdef in snap[d]['parameters'].get('properties', {}).items():
            rev = [k for k, v in remap.items() if v == pname]
            tn = rev[0] if rev else pname
            if tn in props:
                e = props[tn]
                if 'enum' in e and 'enum' in pdef:
                    for v in pdef['enum']:
                        if v not in e['enum']:
                            e['enum'].append(v)
                continue
            p = {"type": pdef['type']}
            if 'enum' in pdef:
                p['enum'] = list(pdef['enum'])
            p['description'] = pdef.get('description', '')
            props[tn] = p
    for k, v in (extra or {}).items():
        props[k] = v
    return {"type": "object", "properties": props, "required": ["action"]}


def strip_titles(o):
    if isinstance(o, dict):
        return {k: strip_titles(v) for k, v in o.items() if k != 'title'}
    if isinstance(o, list):
        return [strip_titles(x) for x in o]
    return o


def zig_const(name, obj):
    lines = json.dumps(obj, indent=2, ensure_ascii=False).split('\n')
    return 'pub const %s =\n%s\n;\n' % (name, '\n'.join('    \\\\' + ln for ln in lines))


print('//! Generated by gen_schemas.py from computer_control_mcp 0.3.10 (FastMCP list_tools)')
print('//! and clawdcursor 0.9.3 (schema.snapshot.json + compact.ts). Do not edit by hand.')
print()
for t in cc:
    s = strip_titles(t['inputSchema'])
    if t['name'] == 'take_screenshot':
        s['properties']['max_width'] = {"type": "integer", "description": "zmcp extension: downscale so the image is at most this many pixels wide (default: full resolution)."}
    print(zig_const('cc_' + t['name'], s))

computer = compound(routes('COMPUTER_ACTIONS'), {
    "key": {"type": "string", "description": "Alias for combo (the granular key_press parameter name)."},
})
window = compound(routes('WINDOW_ACTIONS'), {
    "confirm": {"type": "boolean", "description": "Required (true) for action=close: closing can lose unsaved work."},
})
system = compound(routes('SYSTEM_ACTIONS'))
print(zig_const('computer', computer))
print(zig_const('window', window))
print(zig_const('system', system))
