//! Generated by gen_schemas.py from computer_control_mcp 0.3.10 (FastMCP list_tools)
//! and clawdcursor 0.9.3 (schema.snapshot.json + compact.ts). Do not edit by hand.

pub const cc_click_screen =
    \\{
    \\  "properties": {
    \\    "x": {
    \\      "type": "integer"
    \\    },
    \\    "y": {
    \\      "type": "integer"
    \\    }
    \\  },
    \\  "required": [
    \\    "x",
    \\    "y"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_get_screen_size =
    \\{
    \\  "properties": {},
    \\  "type": "object"
    \\}
;

pub const cc_type_text =
    \\{
    \\  "properties": {
    \\    "text": {
    \\      "type": "string"
    \\    }
    \\  },
    \\  "required": [
    \\    "text"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_take_screenshot =
    \\{
    \\  "properties": {
    \\    "title_pattern": {
    \\      "default": null,
    \\      "type": "string"
    \\    },
    \\    "use_regex": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    },
    \\    "threshold": {
    \\      "default": 10,
    \\      "type": "integer"
    \\    },
    \\    "scale_percent_for_ocr": {
    \\      "default": null,
    \\      "type": "integer"
    \\    },
    \\    "save_to_downloads": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    },
    \\    "use_wgc": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    },
    \\    "max_width": {
    \\      "type": "integer",
    \\      "description": "zmcp extension: downscale so the image is at most this many pixels wide (default: full resolution)."
    \\    }
    \\  },
    \\  "type": "object"
    \\}
;

pub const cc_take_screenshot_with_ocr =
    \\{
    \\  "properties": {
    \\    "title_pattern": {
    \\      "default": null,
    \\      "type": "string"
    \\    },
    \\    "use_regex": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    },
    \\    "threshold": {
    \\      "default": 10,
    \\      "type": "integer"
    \\    },
    \\    "scale_percent_for_ocr": {
    \\      "default": null,
    \\      "type": "integer"
    \\    },
    \\    "save_to_downloads": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    }
    \\  },
    \\  "type": "object"
    \\}
;

pub const cc_move_mouse =
    \\{
    \\  "properties": {
    \\    "x": {
    \\      "type": "integer"
    \\    },
    \\    "y": {
    \\      "type": "integer"
    \\    }
    \\  },
    \\  "required": [
    \\    "x",
    \\    "y"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_mouse_down =
    \\{
    \\  "properties": {
    \\    "button": {
    \\      "default": "left",
    \\      "type": "string"
    \\    }
    \\  },
    \\  "type": "object"
    \\}
;

pub const cc_mouse_up =
    \\{
    \\  "properties": {
    \\    "button": {
    \\      "default": "left",
    \\      "type": "string"
    \\    }
    \\  },
    \\  "type": "object"
    \\}
;

pub const cc_drag_mouse =
    \\{
    \\  "properties": {
    \\    "from_x": {
    \\      "type": "integer"
    \\    },
    \\    "from_y": {
    \\      "type": "integer"
    \\    },
    \\    "to_x": {
    \\      "type": "integer"
    \\    },
    \\    "to_y": {
    \\      "type": "integer"
    \\    },
    \\    "duration": {
    \\      "default": 0.5,
    \\      "type": "number"
    \\    }
    \\  },
    \\  "required": [
    \\    "from_x",
    \\    "from_y",
    \\    "to_x",
    \\    "to_y"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_key_down =
    \\{
    \\  "properties": {
    \\    "key": {
    \\      "type": "string"
    \\    }
    \\  },
    \\  "required": [
    \\    "key"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_key_up =
    \\{
    \\  "properties": {
    \\    "key": {
    \\      "type": "string"
    \\    }
    \\  },
    \\  "required": [
    \\    "key"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_press_keys =
    \\{
    \\  "properties": {
    \\    "keys": {
    \\      "anyOf": [
    \\        {
    \\          "type": "string"
    \\        },
    \\        {
    \\          "items": {
    \\            "anyOf": [
    \\              {
    \\                "type": "string"
    \\              },
    \\              {
    \\                "items": {
    \\                  "type": "string"
    \\                },
    \\                "type": "array"
    \\              }
    \\            ]
    \\          },
    \\          "type": "array"
    \\        }
    \\      ]
    \\    }
    \\  },
    \\  "required": [
    \\    "keys"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_list_windows =
    \\{
    \\  "properties": {},
    \\  "type": "object"
    \\}
;

pub const cc_wait_milliseconds =
    \\{
    \\  "properties": {
    \\    "milliseconds": {
    \\      "type": "integer"
    \\    }
    \\  },
    \\  "required": [
    \\    "milliseconds"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const cc_activate_window =
    \\{
    \\  "properties": {
    \\    "title_pattern": {
    \\      "type": "string"
    \\    },
    \\    "use_regex": {
    \\      "default": false,
    \\      "type": "boolean"
    \\    },
    \\    "threshold": {
    \\      "default": 60,
    \\      "type": "integer"
    \\    }
    \\  },
    \\  "required": [
    \\    "title_pattern"
    \\  ],
    \\  "type": "object"
    \\}
;

pub const computer =
    \\{
    \\  "type": "object",
    \\  "properties": {
    \\    "action": {
    \\      "type": "string",
    \\      "enum": [
    \\        "screenshot",
    \\        "screenshot_region",
    \\        "click",
    \\        "double_click",
    \\        "right_click",
    \\        "middle_click",
    \\        "triple_click",
    \\        "hover",
    \\        "move",
    \\        "move_relative",
    \\        "scroll",
    \\        "scroll_horizontal",
    \\        "drag",
    \\        "drag_path",
    \\        "mouse_down",
    \\        "mouse_up",
    \\        "type",
    \\        "key",
    \\        "key_press",
    \\        "key_down",
    \\        "key_up",
    \\        "wait"
    \\      ],
    \\      "description": "Which sub-action to perform. See this tool's description for the enum of valid values."
    \\    },
    \\    "x": {
    \\      "type": "number",
    \\      "description": "Left edge X in image-space coordinates"
    \\    },
    \\    "y": {
    \\      "type": "number",
    \\      "description": "Top edge Y in image-space coordinates"
    \\    },
    \\    "width": {
    \\      "type": "number",
    \\      "description": "Width in image-space pixels"
    \\    },
    \\    "height": {
    \\      "type": "number",
    \\      "description": "Height in image-space pixels"
    \\    },
    \\    "dx": {
    \\      "type": "number",
    \\      "description": "X offset in image-space pixels"
    \\    },
    \\    "dy": {
    \\      "type": "number",
    \\      "description": "Y offset in image-space pixels"
    \\    },
    \\    "direction": {
    \\      "type": "string",
    \\      "enum": [
    \\        "up",
    \\        "down",
    \\        "left",
    \\        "right"
    \\      ],
    \\      "description": "Scroll direction"
    \\    },
    \\    "amount": {
    \\      "type": "number",
    \\      "description": "Scroll amount in wheel ticks (default: 3)"
    \\    },
    \\    "startX": {
    \\      "type": "number",
    \\      "description": "Start X in image-space"
    \\    },
    \\    "startY": {
    \\      "type": "number",
    \\      "description": "Start Y in image-space"
    \\    },
    \\    "endX": {
    \\      "type": "number",
    \\      "description": "End X in image-space"
    \\    },
    \\    "endY": {
    \\      "type": "number",
    \\      "description": "End Y in image-space"
    \\    },
    \\    "x1": {
    \\      "type": "number",
    \\      "description": "Alias for startX"
    \\    },
    \\    "y1": {
    \\      "type": "number",
    \\      "description": "Alias for startY"
    \\    },
    \\    "x2": {
    \\      "type": "number",
    \\      "description": "Alias for endX"
    \\    },
    \\    "y2": {
    \\      "type": "number",
    \\      "description": "Alias for endY"
    \\    },
    \\    "path": {
    \\      "type": "string",
    \\      "description": "JSON array of {\"x\":n, \"y\":n} points in image-space, min 2 points"
    \\    },
    \\    "button": {
    \\      "type": "string",
    \\      "enum": [
    \\        "left",
    \\        "right",
    \\        "middle"
    \\      ],
    \\      "description": "Which button (default: left)"
    \\    },
    \\    "text": {
    \\      "type": "string",
    \\      "description": "The text to type"
    \\    },
    \\    "combo": {
    \\      "type": "string",
    \\      "description": "Key or combo to press (e.g. \"Return\", \"ctrl+a\", \"F5\", \"Escape\")"
    \\    },
    \\    "seconds": {
    \\      "type": "number",
    \\      "description": "Duration to wait (0.1 to 30)"
    \\    },
    \\    "key": {
    \\      "type": "string",
    \\      "description": "Alias for combo (the granular key_press parameter name)."
    \\    }
    \\  },
    \\  "required": [
    \\    "action"
    \\  ]
    \\}
;

pub const window =
    \\{
    \\  "type": "object",
    \\  "properties": {
    \\    "action": {
    \\      "type": "string",
    \\      "enum": [
    \\        "list",
    \\        "active",
    \\        "focus",
    \\        "maximize",
    \\        "minimize",
    \\        "restore",
    \\        "close",
    \\        "resize",
    \\        "list_displays",
    \\        "screen_size",
    \\        "open_app",
    \\        "open_file",
    \\        "open_url",
    \\        "switch_tab",
    \\        "navigate"
    \\      ],
    \\      "description": "Which sub-action to perform. See this tool's description for the enum of valid values."
    \\    },
    \\    "processName": {
    \\      "type": "string",
    \\      "description": "Process name to focus (e.g. \"notepad\", \"msedge\")"
    \\    },
    \\    "processId": {
    \\      "type": "number",
    \\      "description": "Process ID to focus"
    \\    },
    \\    "title": {
    \\      "type": "string",
    \\      "description": "Window title substring to match"
    \\    },
    \\    "x": {
    \\      "type": "number",
    \\      "description": "New X (top-left origin, logical px)"
    \\    },
    \\    "y": {
    \\      "type": "number",
    \\      "description": "New Y (top-left origin, logical px)"
    \\    },
    \\    "width": {
    \\      "type": "number",
    \\      "description": "New width in logical px"
    \\    },
    \\    "height": {
    \\      "type": "number",
    \\      "description": "New height in logical px"
    \\    },
    \\    "name": {
    \\      "type": "string",
    \\      "description": "Application name (e.g. \"notepad\", \"calc\", \"mspaint\", \"Outlook\", \"Chrome\")"
    \\    },
    \\    "path": {
    \\      "type": "string",
    \\      "description": "Absolute filesystem path"
    \\    },
    \\    "url": {
    \\      "type": "string",
    \\      "description": "https:// or http:// URL"
    \\    },
    \\    "index": {
    \\      "type": "number",
    \\      "description": "Jump to tab N (1-based, 1-9). If omitted, direction must be provided."
    \\    },
    \\    "direction": {
    \\      "type": "string",
    \\      "enum": [
    \\        "next",
    \\        "previous"
    \\      ],
    \\      "description": "Cycle \"next\" or \"previous\". Ignored when `index` is given."
    \\    },
    \\    "confirm": {
    \\      "type": "boolean",
    \\      "description": "Required (true) for action=close: closing can lose unsaved work."
    \\    }
    \\  },
    \\  "required": [
    \\    "action"
    \\  ]
    \\}
;

pub const system =
    \\{
    \\  "type": "object",
    \\  "properties": {
    \\    "action": {
    \\      "type": "string",
    \\      "enum": [
    \\        "clipboard_read",
    \\        "clipboard_write",
    \\        "system_time",
    \\        "ocr",
    \\        "undo",
    \\        "shortcuts_list",
    \\        "shortcuts_run",
    \\        "delegate",
    \\        "detect_webview",
    \\        "relaunch_with_cdp",
    \\        "app_guide",
    \\        "detect_app",
    \\        "classify_task",
    \\        "system_prompt"
    \\      ],
    \\      "description": "Which sub-action to perform. See this tool's description for the enum of valid values."
    \\    },
    \\    "text": {
    \\      "type": "string",
    \\      "description": "Text to write to clipboard"
    \\    },
    \\    "category": {
    \\      "type": "string",
    \\      "enum": [
    \\        "navigation",
    \\        "browser",
    \\        "editing",
    \\        "social",
    \\        "window",
    \\        "file",
    \\        "view",
    \\        "quick"
    \\      ],
    \\      "description": "Filter by category: navigation, browser, editing, social, window, file, view, quick. Omit to list all."
    \\    },
    \\    "context": {
    \\      "type": "string",
    \\      "description": "Filter by app context (e.g. \"reddit\", \"outlook\", \"x.com\"). Shows context-specific shortcuts that match."
    \\    },
    \\    "intent": {
    \\      "type": "string",
    \\      "description": "What you want to do (e.g. \"scroll down\", \"new tab\", \"copy\", \"upvote\", \"reply to email\")"
    \\    },
    \\    "task": {
    \\      "type": "string",
    \\      "description": "Natural language task description"
    \\    },
    \\    "timeout": {
    \\      "type": "number",
    \\      "description": "Timeout in seconds (default: 300)"
    \\    },
    \\    "appName": {
    \\      "type": "string",
    \\      "description": "Process name of the app (e.g. \"discord\", \"slack\", \"olk\")"
    \\    },
    \\    "port": {
    \\      "type": "number",
    \\      "description": "Port to open for CDP. Default 9222."
    \\    },
    \\    "app": {
    \\      "type": "string",
    \\      "description": "Canonical app key (e.g. \"gmail\", \"youtube\", \"outlook\")"
    \\    },
    \\    "urlOrTitle": {
    \\      "type": "string",
    \\      "description": "URL or window title to resolve into an app key"
    \\    },
    \\    "activeWindowTitle": {
    \\      "type": "string",
    \\      "description": "Optional active window title for app-detection context"
    \\    },
    \\    "activeWindowProcessName": {
    \\      "type": "string",
    \\      "description": "Optional active window process name for app-detection context"
    \\    },
    \\    "mode": {
    \\      "type": "string",
    \\      "enum": [
    \\        "blind",
    \\        "hybrid",
    \\        "vision"
    \\      ],
    \\      "description": "Agent mode: \"blind\" (a11y only), \"hybrid\" (a11y + on-demand screenshots), or \"vision\" (screenshot per turn)"
    \\    }
    \\  },
    \\  "required": [
    \\    "action"
    \\  ]
    \\}
;

