//! Generated from clawdcursor src/shortcuts.ts (v0.9.3) by gen_shortcuts.py.
//! Windows bindings only (keys.win32 ?? keys.default); entries with no Windows binding are dropped.

pub const Shortcut = struct {
    id: []const u8,
    category: []const u8,
    description: []const u8,
    intent: []const u8,
    intents: []const []const u8,
    key: []const u8,
    context: []const []const u8 = &.{},
};

pub const all = [_]Shortcut{
    .{ .id = "scroll-down", .category = "navigation", .description = "Scroll down one page", .intent = "scroll down", .intents = &.{ "scroll down", "page down", "move down a page" }, .key = "PageDown" },
    .{ .id = "scroll-up", .category = "navigation", .description = "Scroll up one page", .intent = "scroll up", .intents = &.{ "scroll up", "page up", "move up a page" }, .key = "PageUp" },
    .{ .id = "go-top", .category = "navigation", .description = "Go to top of page", .intent = "go to top", .intents = &.{ "go to top", "jump to top", "top of page" }, .key = "Control+Home" },
    .{ .id = "go-bottom", .category = "navigation", .description = "Go to bottom of page", .intent = "go to bottom", .intents = &.{ "go to bottom", "jump to bottom", "bottom of page" }, .key = "Control+End" },
    .{ .id = "home", .category = "navigation", .description = "Go to line/page start", .intent = "home", .intents = &.{ "home", "go home" }, .key = "Home" },
    .{ .id = "end", .category = "navigation", .description = "Go to line/page end", .intent = "end", .intents = &.{ "end", "go end" }, .key = "End" },
    .{ .id = "new-tab", .category = "browser", .description = "Open new browser tab", .intent = "new tab", .intents = &.{ "new tab", "open new tab" }, .key = "Control+t" },
    .{ .id = "close-tab", .category = "browser", .description = "Close current browser tab", .intent = "close tab", .intents = &.{ "close tab", "close this tab" }, .key = "Control+w" },
    .{ .id = "reopen-tab", .category = "browser", .description = "Reopen last closed tab", .intent = "reopen tab", .intents = &.{ "reopen tab", "undo close tab", "restore tab" }, .key = "Control+Shift+t" },
    .{ .id = "refresh", .category = "browser", .description = "Refresh current page", .intent = "refresh", .intents = &.{ "refresh", "reload page", "reload" }, .key = "F5" },
    .{ .id = "hard-refresh", .category = "browser", .description = "Hard refresh current page", .intent = "hard refresh", .intents = &.{ "hard refresh", "force refresh" }, .key = "Control+F5" },
    .{ .id = "go-back", .category = "browser", .description = "Go back in history", .intent = "go back", .intents = &.{ "go back", "back" }, .key = "Alt+Left" },
    .{ .id = "go-forward", .category = "browser", .description = "Go forward in history", .intent = "go forward", .intents = &.{ "go forward", "forward" }, .key = "Alt+Right" },
    .{ .id = "address-bar", .category = "browser", .description = "Focus address bar", .intent = "focus address bar", .intents = &.{ "focus address bar", "url bar", "go to address bar" }, .key = "Control+l" },
    .{ .id = "dev-tools", .category = "browser", .description = "Toggle developer tools", .intent = "open dev tools", .intents = &.{ "dev tools", "open dev tools", "toggle developer tools" }, .key = "Control+Shift+i" },
    .{ .id = "copy", .category = "editing", .description = "Copy selection", .intent = "copy", .intents = &.{ "copy", "copy this" }, .key = "Control+c" },
    .{ .id = "paste", .category = "editing", .description = "Paste clipboard", .intent = "paste", .intents = &.{ "paste", "paste here" }, .key = "Control+v" },
    .{ .id = "cut", .category = "editing", .description = "Cut selection", .intent = "cut", .intents = &.{ "cut" }, .key = "Control+x" },
    .{ .id = "undo", .category = "editing", .description = "Undo previous action", .intent = "undo", .intents = &.{ "undo" }, .key = "Control+z" },
    .{ .id = "redo", .category = "editing", .description = "Redo previous action", .intent = "redo", .intents = &.{ "redo" }, .key = "Control+y" },
    .{ .id = "select-all", .category = "editing", .description = "Select all content", .intent = "select all", .intents = &.{ "select all" }, .key = "Control+a" },
    .{ .id = "find", .category = "editing", .description = "Find in current context", .intent = "find", .intents = &.{ "search in page", "find in page", "find on page", "find text" }, .key = "Control+f" },
    .{ .id = "replace", .category = "editing", .description = "Find and replace", .intent = "replace", .intents = &.{ "replace", "find and replace" }, .key = "Control+h" },
    .{ .id = "reddit-upvote", .category = "social", .description = "Upvote current post/comment", .intent = "upvote", .intents = &.{ "upvote", "reddit upvote" }, .key = "a", .context = &.{ "reddit" } },
    .{ .id = "reddit-downvote", .category = "social", .description = "Downvote current post/comment", .intent = "downvote", .intents = &.{ "downvote", "reddit downvote" }, .key = "z", .context = &.{ "reddit" } },
    .{ .id = "reddit-next", .category = "social", .description = "Move to next post", .intent = "next post", .intents = &.{ "next post", "next item", "reddit next" }, .key = "j", .context = &.{ "reddit" } },
    .{ .id = "reddit-prev", .category = "social", .description = "Move to previous post", .intent = "previous post", .intents = &.{ "previous post", "previous item", "reddit previous" }, .key = "k", .context = &.{ "reddit" } },
    .{ .id = "reddit-comments", .category = "social", .description = "Open comments", .intent = "open comments", .intents = &.{ "open comments", "view comments" }, .key = "c", .context = &.{ "reddit" } },
    .{ .id = "reddit-save", .category = "social", .description = "Save current post", .intent = "save post", .intents = &.{ "save post" }, .key = "s", .context = &.{ "reddit" } },
    .{ .id = "x-like", .category = "social", .description = "Like tweet", .intent = "like tweet", .intents = &.{ "like tweet", "like post" }, .key = "l", .context = &.{ "twitter", "x.com", "tweet" } },
    .{ .id = "x-retweet", .category = "social", .description = "Retweet tweet", .intent = "retweet", .intents = &.{ "retweet", "repost" }, .key = "t", .context = &.{ "twitter", "x.com", "tweet" } },
    .{ .id = "switch-app", .category = "window", .description = "Switch to next application", .intent = "switch app", .intents = &.{ "switch app", "next app", "alt tab" }, .key = "Alt+Tab" },
    .{ .id = "switch-app-reverse", .category = "window", .description = "Switch to previous application", .intent = "switch previous app", .intents = &.{ "previous app", "reverse app switch" }, .key = "Alt+Shift+Tab" },
    .{ .id = "close-window", .category = "window", .description = "Close current window", .intent = "close window", .intents = &.{ "close window" }, .key = "Alt+F4" },
    .{ .id = "minimize-window", .category = "window", .description = "Minimize current window", .intent = "minimize window", .intents = &.{ "minimize window" }, .key = "Super+Down" },
    .{ .id = "maximize-window", .category = "window", .description = "Maximize current window", .intent = "maximize window", .intents = &.{ "maximize window" }, .key = "Super+Up" },
    .{ .id = "show-desktop", .category = "window", .description = "Show desktop", .intent = "show desktop", .intents = &.{ "show desktop", "go to desktop", "minimize all" }, .key = "Super+d" },
    .{ .id = "save", .category = "file", .description = "Save current file", .intent = "save", .intents = &.{ "save", "save file" }, .key = "Control+s" },
    .{ .id = "save-as", .category = "file", .description = "Save current file as", .intent = "save as", .intents = &.{ "save as" }, .key = "Control+Shift+s" },
    .{ .id = "open-file", .category = "file", .description = "Open file", .intent = "open file", .intents = &.{ "open file" }, .key = "Control+o" },
    .{ .id = "new-file", .category = "file", .description = "Create new file", .intent = "new file", .intents = &.{ "new file" }, .key = "Control+n" },
    .{ .id = "print", .category = "file", .description = "Print current document", .intent = "print", .intents = &.{ "print", "print page" }, .key = "Control+p" },
    .{ .id = "zoom-in", .category = "view", .description = "Zoom in", .intent = "zoom in", .intents = &.{ "zoom in", "increase zoom" }, .key = "Control+=" },
    .{ .id = "zoom-out", .category = "view", .description = "Zoom out", .intent = "zoom out", .intents = &.{ "zoom out", "decrease zoom" }, .key = "Control+-" },
    .{ .id = "zoom-reset", .category = "view", .description = "Reset zoom", .intent = "reset zoom", .intents = &.{ "reset zoom", "normal zoom" }, .key = "Control+0" },
    .{ .id = "fullscreen", .category = "view", .description = "Toggle fullscreen", .intent = "fullscreen", .intents = &.{ "fullscreen", "toggle fullscreen" }, .key = "F11" },
    .{ .id = "escape", .category = "quick", .description = "Cancel or close current dialog", .intent = "press escape", .intents = &.{ "escape", "press escape", "esc" }, .key = "Escape" },
    .{ .id = "enter", .category = "quick", .description = "Confirm current action", .intent = "press enter", .intents = &.{ "enter", "press enter", "return" }, .key = "Return" },
    .{ .id = "tab", .category = "quick", .description = "Move to next field", .intent = "press tab", .intents = &.{ "tab", "press tab" }, .key = "Tab" },
    .{ .id = "space", .category = "quick", .description = "Toggle focused control", .intent = "press space", .intents = &.{ "space", "press space", "spacebar" }, .key = "Space" },
    .{ .id = "delete", .category = "quick", .description = "Delete selection", .intent = "press delete", .intents = &.{ "delete", "press delete" }, .key = "Delete" },
    .{ .id = "system-search", .category = "quick", .description = "Open system search", .intent = "system search", .intents = &.{ "system search", "open search", "search apps" }, .key = "Super+s" },
    .{ .id = "lock-screen", .category = "quick", .description = "Lock current session", .intent = "lock screen", .intents = &.{ "lock screen" }, .key = "Super+l" },
    .{ .id = "screenshot-full", .category = "quick", .description = "Take full screenshot", .intent = "screenshot", .intents = &.{ "screenshot", "take screenshot", "capture screen", "print screen" }, .key = "Super+Shift+s" },
    .{ .id = "screenshot-selection", .category = "quick", .description = "Screenshot selection", .intent = "screenshot selection", .intents = &.{ "screenshot selection", "capture area", "screenshot region" }, .key = "Super+Shift+s" },
    .{ .id = "screenshot-window", .category = "quick", .description = "Screenshot or screen recording menu", .intent = "screenshot menu", .intents = &.{ "screenshot menu", "screen recording" }, .key = "Super+Shift+s" },
    .{ .id = "spotlight", .category = "quick", .description = "Open Spotlight / system search", .intent = "spotlight", .intents = &.{ "spotlight", "search apps", "find app", "open spotlight" }, .key = "Super+s" },
    .{ .id = "force-quit", .category = "window", .description = "Force quit application", .intent = "force quit", .intents = &.{ "force quit", "kill app", "force close" }, .key = "Alt+F4" },
    .{ .id = "quit-app", .category = "window", .description = "Quit current application", .intent = "quit app", .intents = &.{ "quit app", "close app", "exit app" }, .key = "Alt+F4" },
    .{ .id = "close-window", .category = "window", .description = "Close front window", .intent = "close window", .intents = &.{ "close window", "close this window" }, .key = "Alt+F4" },
    .{ .id = "close-all-windows", .category = "window", .description = "Close all windows of app", .intent = "close all windows", .intents = &.{ "close all windows", "close all" }, .key = "Alt+F4" },
    .{ .id = "minimize-all", .category = "window", .description = "Minimize all windows of app", .intent = "minimize all", .intents = &.{ "minimize all", "minimize all windows" }, .key = "Super+d" },
    .{ .id = "switch-windows-same-app", .category = "window", .description = "Switch between windows of same app", .intent = "switch windows", .intents = &.{ "switch windows", "next window", "cycle windows" }, .key = "Alt+Tab" },
    .{ .id = "mission-control", .category = "window", .description = "Open Mission Control", .intent = "mission control", .intents = &.{ "mission control", "show all windows", "overview" }, .key = "Super+Tab" },
    .{ .id = "bold", .category = "editing", .description = "Bold text", .intent = "bold", .intents = &.{ "bold", "make bold", "bold text" }, .key = "Control+b" },
    .{ .id = "italic", .category = "editing", .description = "Italic text", .intent = "italic", .intents = &.{ "italic", "make italic", "italicize" }, .key = "Control+i" },
    .{ .id = "underline", .category = "editing", .description = "Underline text", .intent = "underline", .intents = &.{ "underline", "make underline" }, .key = "Control+u" },
    .{ .id = "paste-match-style", .category = "editing", .description = "Paste and match style", .intent = "paste plain", .intents = &.{ "paste plain", "paste without formatting", "paste match style" }, .key = "Control+Shift+v" },
    .{ .id = "emoji-picker", .category = "editing", .description = "Open emoji/character picker", .intent = "emoji", .intents = &.{ "emoji", "emoji picker", "character viewer", "special characters" }, .key = "Super+." },
    .{ .id = "email-new-message", .category = "editing", .description = "Create new email message", .intent = "new email", .intents = &.{ "new email", "new message", "compose email", "compose message", "write email", "create email", "new mail" }, .key = "Control+n", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-send", .category = "editing", .description = "Send email message", .intent = "send email", .intents = &.{ "send email", "send message", "send mail", "send this email", "send it" }, .key = "Control+Return", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-reply", .category = "editing", .description = "Reply to email", .intent = "reply", .intents = &.{ "reply", "reply to email", "reply to message", "reply to this" }, .key = "Control+r", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-reply-all", .category = "editing", .description = "Reply all to email", .intent = "reply all", .intents = &.{ "reply all", "reply to all", "respond to all" }, .key = "Control+Shift+r", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-forward", .category = "editing", .description = "Forward email", .intent = "forward email", .intents = &.{ "forward", "forward email", "forward message", "forward this" }, .key = "Control+f", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-delete", .category = "editing", .description = "Delete email", .intent = "delete email", .intents = &.{ "delete email", "delete message", "delete this email", "trash email" }, .key = "Delete", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-mark-read", .category = "editing", .description = "Mark email as read/unread", .intent = "mark as read", .intents = &.{ "mark as read", "mark read", "mark unread", "mark as unread" }, .key = "Control+q", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "email-check", .category = "editing", .description = "Check for new mail", .intent = "check mail", .intents = &.{ "check mail", "get mail", "refresh", "check for new messages", "fetch mail" }, .key = "F9", .context = &.{ "outlook", "olk", "mail", "thunderbird" } },
    .{ .id = "safari-new-tab", .category = "browser", .description = "New tab in Safari", .intent = "new tab", .intents = &.{ "new tab", "open new tab" }, .key = "Control+t", .context = &.{ "safari" } },
    .{ .id = "safari-address-bar", .category = "browser", .description = "Focus address bar", .intent = "address bar", .intents = &.{ "address bar", "url bar", "location bar" }, .key = "Control+l", .context = &.{ "safari" } },
    .{ .id = "safari-next-tab", .category = "browser", .description = "Next tab", .intent = "next tab", .intents = &.{ "next tab", "switch tab" }, .key = "Control+Tab", .context = &.{ "safari" } },
    .{ .id = "safari-prev-tab", .category = "browser", .description = "Previous tab", .intent = "previous tab", .intents = &.{ "previous tab", "prev tab" }, .key = "Control+Shift+Tab", .context = &.{ "safari" } },
    .{ .id = "safari-close-tab", .category = "browser", .description = "Close tab", .intent = "close tab", .intents = &.{ "close tab" }, .key = "Control+w", .context = &.{ "safari" } },
    .{ .id = "safari-reopen-tab", .category = "browser", .description = "Reopen last closed tab", .intent = "reopen tab", .intents = &.{ "reopen tab", "undo close tab" }, .key = "Control+Shift+t", .context = &.{ "safari" } },
    .{ .id = "notes-new", .category = "editing", .description = "Create new note", .intent = "new note", .intents = &.{ "new note", "create note" }, .key = "Control+n", .context = &.{ "notes" } },
    .{ .id = "notes-search", .category = "editing", .description = "Search all notes", .intent = "search notes", .intents = &.{ "search notes", "find note" }, .key = "Control+f", .context = &.{ "notes" } },
    .{ .id = "notes-link", .category = "editing", .description = "Add web link", .intent = "add link", .intents = &.{ "add link", "insert link", "web link" }, .key = "Control+k", .context = &.{ "notes" } },
    .{ .id = "messages-new", .category = "editing", .description = "Start new message", .intent = "new message", .intents = &.{ "new message", "new text", "new imessage" }, .key = "Control+n", .context = &.{ "messages" } },
    .{ .id = "messages-send", .category = "editing", .description = "Send message", .intent = "send message", .intents = &.{ "send message", "send text", "send it" }, .key = "Return", .context = &.{ "messages" } },
    .{ .id = "messages-newline", .category = "editing", .description = "New line in message", .intent = "new line", .intents = &.{ "new line", "line break" }, .key = "Shift+Return", .context = &.{ "messages" } },
    .{ .id = "messages-search", .category = "editing", .description = "Search conversations", .intent = "search messages", .intents = &.{ "search messages", "find message", "search conversations" }, .key = "Control+f", .context = &.{ "messages" } },
};
