//! GENERATED by src/desktop/gen_uia.py from
//!   the Windows SDK 10.0.22621.0 UIAutomationClient.h (GUIDs, vtable order, constants only)
//! Do not hand-edit: every vtable slot is in header order; untyped slots are
//! `*const anyopaque` placeholders that keep later offsets correct.
//! COM on aarch64-windows uses the plain AAPCS64 C convention (`.winapi` == `.c`),
//! `this` in x0; typed slots return HRESULT/ULONG and take pointers or 32-bit
//! scalars, except CreatePropertyCondition, which takes a VARIANT (24 bytes) by
//! value. Both the x64 MS ABI and AAPCS64 pass a composite over 16 bytes as a
//! pointer to a caller-owned copy; Zig's C-ABI lowering does that for an extern
//! struct parameter. uia.zig has a live test for it on each target.

const std = @import("std");

pub const HRESULT = i32;
pub const GUID = extern struct { data1: u32, data2: u16, data3: u16, data4: [8]u8 };
pub const RECT = extern struct { left: i32, top: i32, right: i32, bottom: i32 };
pub const POINT = extern struct { x: i32, y: i32 };
/// VARIANT: 24 bytes, 8-aligned on 64-bit Windows (x64 and ARM64 alike).
pub const VARIANT = extern struct { vt: u16, r1: u16 = 0, r2: u16 = 0, r3: u16 = 0, data: [2]u64 = .{ 0, 0 } };
comptime {
    std.debug.assert(@sizeOf(VARIANT) == 24 and @alignOf(VARIANT) == 8);
}

/// CLSID_CUIAutomation  {ff48dba4-60ef-4201-aa87-54103eef594e}
pub const CLSID_CUIAutomation: GUID = .{ .data1 = 0xff48dba4, .data2 = 0x60ef, .data3 = 0x4201, .data4 = .{ 0xaa, 0x87, 0x54, 0x10, 0x3e, 0xef, 0x59, 0x4e } };
/// CLSID_CUIAutomation8  {e22ad333-b25f-460c-83d0-0581107395c9}
pub const CLSID_CUIAutomation8: GUID = .{ .data1 = 0xe22ad333, .data2 = 0xb25f, .data3 = 0x460c, .data4 = .{ 0x83, 0xd0, 0x05, 0x81, 0x10, 0x73, 0x95, 0xc9 } };
pub const UIA_BoundingRectanglePropertyId: i32 = 30001;
pub const UIA_ControlTypePropertyId: i32 = 30003;
pub const UIA_NamePropertyId: i32 = 30005;
pub const UIA_AutomationIdPropertyId: i32 = 30011;
pub const UIA_ClassNamePropertyId: i32 = 30012;
pub const UIA_IsKeyboardFocusablePropertyId: i32 = 30009;
pub const UIA_IsEnabledPropertyId: i32 = 30010;
pub const UIA_IsPasswordPropertyId: i32 = 30019;
pub const UIA_RuntimeIdPropertyId: i32 = 30000;
pub const UIA_ProcessIdPropertyId: i32 = 30002;
pub const UIA_HasKeyboardFocusPropertyId: i32 = 30008;
pub const UIA_IsValuePatternAvailablePropertyId: i32 = 30043;
pub const UIA_ValueValuePropertyId: i32 = 30045;
pub const UIA_ValueIsReadOnlyPropertyId: i32 = 30046;
pub const UIA_NativeWindowHandlePropertyId: i32 = 30020;
pub const UIA_IsTextPatternAvailablePropertyId: i32 = 30040;
pub const UIA_InvokePatternId: i32 = 10000;
pub const UIA_ValuePatternId: i32 = 10002;
pub const UIA_SelectionItemPatternId: i32 = 10010;
pub const UIA_ExpandCollapsePatternId: i32 = 10005;
pub const UIA_ScrollItemPatternId: i32 = 10017;
pub const UIA_ScrollPatternId: i32 = 10004;
pub const UIA_TextPatternId: i32 = 10014;
/// IID_IUIAutomation  {30cbe57d-d9d0-452a-ab13-7ac5ac4825ee}
pub const IID_IUIAutomation: GUID = .{ .data1 = 0x30cbe57d, .data2 = 0xd9d0, .data3 = 0x452a, .data4 = .{ 0xab, 0x13, 0x7a, 0xc5, 0xac, 0x48, 0x25, 0xee } };
/// IID_IUIAutomation2  {34723aff-0c9d-49d0-9896-7ab52df8cd8a}
pub const IID_IUIAutomation2: GUID = .{ .data1 = 0x34723aff, .data2 = 0x0c9d, .data3 = 0x49d0, .data4 = .{ 0x98, 0x96, 0x7a, 0xb5, 0x2d, 0xf8, 0xcd, 0x8a } };
/// IID_IUIAutomationElement  {d22108aa-8ac5-49a5-837b-37bbb3d7591e}
pub const IID_IUIAutomationElement: GUID = .{ .data1 = 0xd22108aa, .data2 = 0x8ac5, .data3 = 0x49a5, .data4 = .{ 0x83, 0x7b, 0x37, 0xbb, 0xb3, 0xd7, 0x59, 0x1e } };
/// IID_IUIAutomationElementArray  {14314595-b4bc-4055-95f2-58f2e42c9855}
pub const IID_IUIAutomationElementArray: GUID = .{ .data1 = 0x14314595, .data2 = 0xb4bc, .data3 = 0x4055, .data4 = .{ 0x95, 0xf2, 0x58, 0xf2, 0xe4, 0x2c, 0x98, 0x55 } };
/// IID_IUIAutomationCondition  {352ffba8-0973-437c-a61f-f64cafd81df9}
pub const IID_IUIAutomationCondition: GUID = .{ .data1 = 0x352ffba8, .data2 = 0x0973, .data3 = 0x437c, .data4 = .{ 0xa6, 0x1f, 0xf6, 0x4c, 0xaf, 0xd8, 0x1d, 0xf9 } };
/// IID_IUIAutomationTreeWalker  {4042c624-389c-4afc-a630-9df854a541fc}
pub const IID_IUIAutomationTreeWalker: GUID = .{ .data1 = 0x4042c624, .data2 = 0x389c, .data3 = 0x4afc, .data4 = .{ 0xa6, 0x30, 0x9d, 0xf8, 0x54, 0xa5, 0x41, 0xfc } };
/// IID_IUIAutomationCacheRequest  {b32a92b5-bc25-4078-9c08-d7ee95c48e03}
pub const IID_IUIAutomationCacheRequest: GUID = .{ .data1 = 0xb32a92b5, .data2 = 0xbc25, .data3 = 0x4078, .data4 = .{ 0x9c, 0x08, 0xd7, 0xee, 0x95, 0xc4, 0x8e, 0x03 } };
/// IID_IUIAutomationInvokePattern  {fb377fbe-8ea6-46d5-9c73-6499642d3059}
pub const IID_IUIAutomationInvokePattern: GUID = .{ .data1 = 0xfb377fbe, .data2 = 0x8ea6, .data3 = 0x46d5, .data4 = .{ 0x9c, 0x73, 0x64, 0x99, 0x64, 0x2d, 0x30, 0x59 } };
/// IID_IUIAutomationValuePattern  {a94cd8b1-0844-4cd6-9d2d-640537ab39e9}
pub const IID_IUIAutomationValuePattern: GUID = .{ .data1 = 0xa94cd8b1, .data2 = 0x0844, .data3 = 0x4cd6, .data4 = .{ 0x9d, 0x2d, 0x64, 0x05, 0x37, 0xab, 0x39, 0xe9 } };
/// IID_IUIAutomationSelectionItemPattern  {a8efa66a-0fda-421a-9194-38021f3578ea}
pub const IID_IUIAutomationSelectionItemPattern: GUID = .{ .data1 = 0xa8efa66a, .data2 = 0x0fda, .data3 = 0x421a, .data4 = .{ 0x91, 0x94, 0x38, 0x02, 0x1f, 0x35, 0x78, 0xea } };
/// IID_IUIAutomationExpandCollapsePattern  {619be086-1f4e-4ee4-bafa-210128738730}
pub const IID_IUIAutomationExpandCollapsePattern: GUID = .{ .data1 = 0x619be086, .data2 = 0x1f4e, .data3 = 0x4ee4, .data4 = .{ 0xba, 0xfa, 0x21, 0x01, 0x28, 0x73, 0x87, 0x30 } };
/// IID_IUIAutomationScrollItemPattern  {b488300f-d015-4f19-9c29-bb595e3645ef}
pub const IID_IUIAutomationScrollItemPattern: GUID = .{ .data1 = 0xb488300f, .data2 = 0xd015, .data3 = 0x4f19, .data4 = .{ 0x9c, 0x29, 0xbb, 0x59, 0x5e, 0x36, 0x45, 0xef } };
/// IID_IUIAutomationScrollPattern  {88f4d42a-e881-459d-a77c-73bbbb7e02dc}
pub const IID_IUIAutomationScrollPattern: GUID = .{ .data1 = 0x88f4d42a, .data2 = 0xe881, .data3 = 0x459d, .data4 = .{ 0xa7, 0x7c, 0x73, 0xbb, 0xbb, 0x7e, 0x02, 0xdc } };
/// IID_IUIAutomationTextPattern  {32eba289-3583-42c9-9c59-3b6d9a1e9b6a}
pub const IID_IUIAutomationTextPattern: GUID = .{ .data1 = 0x32eba289, .data2 = 0x3583, .data3 = 0x42c9, .data4 = .{ 0x9c, 0x59, 0x3b, 0x6d, 0x9a, 0x1e, 0x9b, 0x6a } };
/// IID_IUIAutomationTextRange  {a543cc6a-f4ae-494b-8239-c814481187a8}
pub const IID_IUIAutomationTextRange: GUID = .{ .data1 = 0xa543cc6a, .data2 = 0xf4ae, .data3 = 0x494b, .data4 = .{ 0x82, 0x39, 0xc8, 0x14, 0x48, 0x11, 0x87, 0xa8 } };

pub const IUIAutomation = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomation, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomation) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomation) callconv(.winapi) u32, // [2]
        CompareElements: *const anyopaque, // [3]
        CompareRuntimeIds: *const anyopaque, // [4]
        GetRootElement: *const fn (self: *IUIAutomation, root: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [5]
        ElementFromHandle: *const fn (self: *IUIAutomation, hwnd: ?*anyopaque, element: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [6]
        ElementFromPoint: *const anyopaque, // [7]
        GetFocusedElement: *const anyopaque, // [8]
        GetRootElementBuildCache: *const anyopaque, // [9]
        ElementFromHandleBuildCache: *const fn (self: *IUIAutomation, hwnd: ?*anyopaque, req: *IUIAutomationCacheRequest, element: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [10]
        ElementFromPointBuildCache: *const fn (self: *IUIAutomation, pt: POINT, req: *IUIAutomationCacheRequest, element: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [11]
        GetFocusedElementBuildCache: *const fn (self: *IUIAutomation, req: *IUIAutomationCacheRequest, element: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [12]
        CreateTreeWalker: *const anyopaque, // [13]
        get_ControlViewWalker: *const fn (self: *IUIAutomation, walker: *?*IUIAutomationTreeWalker) callconv(.winapi) HRESULT, // [14]
        get_ContentViewWalker: *const anyopaque, // [15]
        get_RawViewWalker: *const anyopaque, // [16]
        get_RawViewCondition: *const anyopaque, // [17]
        get_ControlViewCondition: *const fn (self: *IUIAutomation, cond: *?*IUIAutomationCondition) callconv(.winapi) HRESULT, // [18]
        get_ContentViewCondition: *const anyopaque, // [19]
        CreateCacheRequest: *const fn (self: *IUIAutomation, req: *?*IUIAutomationCacheRequest) callconv(.winapi) HRESULT, // [20]
        CreateTrueCondition: *const anyopaque, // [21]
        CreateFalseCondition: *const anyopaque, // [22]
        CreatePropertyCondition: *const fn (self: *IUIAutomation, property_id: i32, value: VARIANT, cond: *?*IUIAutomationCondition) callconv(.winapi) HRESULT, // [23]
        CreatePropertyConditionEx: *const anyopaque, // [24]
        CreateAndCondition: *const fn (self: *IUIAutomation, c1: *IUIAutomationCondition, c2: *IUIAutomationCondition, cond: *?*IUIAutomationCondition) callconv(.winapi) HRESULT, // [25]
        CreateAndConditionFromArray: *const anyopaque, // [26]
        CreateAndConditionFromNativeArray: *const anyopaque, // [27]
        CreateOrCondition: *const fn (self: *IUIAutomation, c1: *IUIAutomationCondition, c2: *IUIAutomationCondition, cond: *?*IUIAutomationCondition) callconv(.winapi) HRESULT, // [28]
        CreateOrConditionFromArray: *const anyopaque, // [29]
        CreateOrConditionFromNativeArray: *const anyopaque, // [30]
        CreateNotCondition: *const anyopaque, // [31]
        AddAutomationEventHandler: *const anyopaque, // [32]
        RemoveAutomationEventHandler: *const anyopaque, // [33]
        AddPropertyChangedEventHandlerNativeArray: *const anyopaque, // [34]
        AddPropertyChangedEventHandler: *const anyopaque, // [35]
        RemovePropertyChangedEventHandler: *const anyopaque, // [36]
        AddStructureChangedEventHandler: *const anyopaque, // [37]
        RemoveStructureChangedEventHandler: *const anyopaque, // [38]
        AddFocusChangedEventHandler: *const anyopaque, // [39]
        RemoveFocusChangedEventHandler: *const anyopaque, // [40]
        RemoveAllEventHandlers: *const anyopaque, // [41]
        IntNativeArrayToSafeArray: *const anyopaque, // [42]
        IntSafeArrayToNativeArray: *const anyopaque, // [43]
        RectToVariant: *const anyopaque, // [44]
        VariantToRect: *const anyopaque, // [45]
        SafeArrayToRectNativeArray: *const anyopaque, // [46]
        CreateProxyFactoryEntry: *const anyopaque, // [47]
        get_ProxyFactoryMapping: *const anyopaque, // [48]
        GetPropertyProgrammaticName: *const anyopaque, // [49]
        GetPatternProgrammaticName: *const anyopaque, // [50]
        PollForPotentialSupportedPatterns: *const anyopaque, // [51]
        PollForPotentialSupportedProperties: *const anyopaque, // [52]
        CheckNotSupported: *const anyopaque, // [53]
        get_ReservedNotSupportedValue: *const anyopaque, // [54]
        get_ReservedMixedAttributeValue: *const anyopaque, // [55]
        ElementFromIAccessible: *const anyopaque, // [56]
        ElementFromIAccessibleBuildCache: *const anyopaque, // [57]
    };
    pub const slot_count = 58;
};

pub const IUIAutomation2 = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomation2, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomation2) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomation2) callconv(.winapi) u32, // [2]
        CompareElements: *const anyopaque, // [3]
        CompareRuntimeIds: *const anyopaque, // [4]
        GetRootElement: *const anyopaque, // [5]
        ElementFromHandle: *const anyopaque, // [6]
        ElementFromPoint: *const anyopaque, // [7]
        GetFocusedElement: *const anyopaque, // [8]
        GetRootElementBuildCache: *const anyopaque, // [9]
        ElementFromHandleBuildCache: *const anyopaque, // [10]
        ElementFromPointBuildCache: *const anyopaque, // [11]
        GetFocusedElementBuildCache: *const anyopaque, // [12]
        CreateTreeWalker: *const anyopaque, // [13]
        get_ControlViewWalker: *const anyopaque, // [14]
        get_ContentViewWalker: *const anyopaque, // [15]
        get_RawViewWalker: *const anyopaque, // [16]
        get_RawViewCondition: *const anyopaque, // [17]
        get_ControlViewCondition: *const anyopaque, // [18]
        get_ContentViewCondition: *const anyopaque, // [19]
        CreateCacheRequest: *const anyopaque, // [20]
        CreateTrueCondition: *const anyopaque, // [21]
        CreateFalseCondition: *const anyopaque, // [22]
        CreatePropertyCondition: *const anyopaque, // [23]
        CreatePropertyConditionEx: *const anyopaque, // [24]
        CreateAndCondition: *const anyopaque, // [25]
        CreateAndConditionFromArray: *const anyopaque, // [26]
        CreateAndConditionFromNativeArray: *const anyopaque, // [27]
        CreateOrCondition: *const anyopaque, // [28]
        CreateOrConditionFromArray: *const anyopaque, // [29]
        CreateOrConditionFromNativeArray: *const anyopaque, // [30]
        CreateNotCondition: *const anyopaque, // [31]
        AddAutomationEventHandler: *const anyopaque, // [32]
        RemoveAutomationEventHandler: *const anyopaque, // [33]
        AddPropertyChangedEventHandlerNativeArray: *const anyopaque, // [34]
        AddPropertyChangedEventHandler: *const anyopaque, // [35]
        RemovePropertyChangedEventHandler: *const anyopaque, // [36]
        AddStructureChangedEventHandler: *const anyopaque, // [37]
        RemoveStructureChangedEventHandler: *const anyopaque, // [38]
        AddFocusChangedEventHandler: *const anyopaque, // [39]
        RemoveFocusChangedEventHandler: *const anyopaque, // [40]
        RemoveAllEventHandlers: *const anyopaque, // [41]
        IntNativeArrayToSafeArray: *const anyopaque, // [42]
        IntSafeArrayToNativeArray: *const anyopaque, // [43]
        RectToVariant: *const anyopaque, // [44]
        VariantToRect: *const anyopaque, // [45]
        SafeArrayToRectNativeArray: *const anyopaque, // [46]
        CreateProxyFactoryEntry: *const anyopaque, // [47]
        get_ProxyFactoryMapping: *const anyopaque, // [48]
        GetPropertyProgrammaticName: *const anyopaque, // [49]
        GetPatternProgrammaticName: *const anyopaque, // [50]
        PollForPotentialSupportedPatterns: *const anyopaque, // [51]
        PollForPotentialSupportedProperties: *const anyopaque, // [52]
        CheckNotSupported: *const anyopaque, // [53]
        get_ReservedNotSupportedValue: *const anyopaque, // [54]
        get_ReservedMixedAttributeValue: *const anyopaque, // [55]
        ElementFromIAccessible: *const anyopaque, // [56]
        ElementFromIAccessibleBuildCache: *const anyopaque, // [57]
        get_AutoSetFocus: *const anyopaque, // [58]
        put_AutoSetFocus: *const anyopaque, // [59]
        get_ConnectionTimeout: *const fn (self: *IUIAutomation2, timeout_ms: *u32) callconv(.winapi) HRESULT, // [60]
        put_ConnectionTimeout: *const fn (self: *IUIAutomation2, timeout_ms: u32) callconv(.winapi) HRESULT, // [61]
        get_TransactionTimeout: *const fn (self: *IUIAutomation2, timeout_ms: *u32) callconv(.winapi) HRESULT, // [62]
        put_TransactionTimeout: *const fn (self: *IUIAutomation2, timeout_ms: u32) callconv(.winapi) HRESULT, // [63]
    };
    pub const slot_count = 64;
};

pub const IUIAutomationElement = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationElement, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationElement) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationElement) callconv(.winapi) u32, // [2]
        SetFocus: *const fn (self: *IUIAutomationElement) callconv(.winapi) HRESULT, // [3]
        GetRuntimeId: *const anyopaque, // [4]
        FindFirst: *const anyopaque, // [5]
        FindAll: *const anyopaque, // [6]
        FindFirstBuildCache: *const fn (self: *IUIAutomationElement, scope: i32, cond: *IUIAutomationCondition, req: *IUIAutomationCacheRequest, found: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [7]
        FindAllBuildCache: *const fn (self: *IUIAutomationElement, scope: i32, cond: *IUIAutomationCondition, req: *IUIAutomationCacheRequest, found: *?*IUIAutomationElementArray) callconv(.winapi) HRESULT, // [8]
        BuildUpdatedCache: *const fn (self: *IUIAutomationElement, req: *IUIAutomationCacheRequest, updated: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [9]
        GetCurrentPropertyValue: *const fn (self: *IUIAutomationElement, property_id: i32, ret: *VARIANT) callconv(.winapi) HRESULT, // [10]
        GetCurrentPropertyValueEx: *const anyopaque, // [11]
        GetCachedPropertyValue: *const fn (self: *IUIAutomationElement, property_id: i32, ret: *VARIANT) callconv(.winapi) HRESULT, // [12]
        GetCachedPropertyValueEx: *const anyopaque, // [13]
        GetCurrentPatternAs: *const anyopaque, // [14]
        GetCachedPatternAs: *const anyopaque, // [15]
        GetCurrentPattern: *const fn (self: *IUIAutomationElement, pattern_id: i32, pattern: *?*anyopaque) callconv(.winapi) HRESULT, // [16]
        GetCachedPattern: *const anyopaque, // [17]
        GetCachedParent: *const anyopaque, // [18]
        GetCachedChildren: *const fn (self: *IUIAutomationElement, ret: *?*IUIAutomationElementArray) callconv(.winapi) HRESULT, // [19]
        get_CurrentProcessId: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [20]
        get_CurrentControlType: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [21]
        get_CurrentLocalizedControlType: *const anyopaque, // [22]
        get_CurrentName: *const fn (self: *IUIAutomationElement, ret: *?[*]u16) callconv(.winapi) HRESULT, // [23]
        get_CurrentAcceleratorKey: *const anyopaque, // [24]
        get_CurrentAccessKey: *const anyopaque, // [25]
        get_CurrentHasKeyboardFocus: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [26]
        get_CurrentIsKeyboardFocusable: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [27]
        get_CurrentIsEnabled: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [28]
        get_CurrentAutomationId: *const anyopaque, // [29]
        get_CurrentClassName: *const fn (self: *IUIAutomationElement, ret: *?[*]u16) callconv(.winapi) HRESULT, // [30]
        get_CurrentHelpText: *const anyopaque, // [31]
        get_CurrentCulture: *const anyopaque, // [32]
        get_CurrentIsControlElement: *const anyopaque, // [33]
        get_CurrentIsContentElement: *const anyopaque, // [34]
        get_CurrentIsPassword: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [35]
        get_CurrentNativeWindowHandle: *const anyopaque, // [36]
        get_CurrentItemType: *const anyopaque, // [37]
        get_CurrentIsOffscreen: *const anyopaque, // [38]
        get_CurrentOrientation: *const anyopaque, // [39]
        get_CurrentFrameworkId: *const anyopaque, // [40]
        get_CurrentIsRequiredForForm: *const anyopaque, // [41]
        get_CurrentItemStatus: *const anyopaque, // [42]
        get_CurrentBoundingRectangle: *const fn (self: *IUIAutomationElement, ret: *RECT) callconv(.winapi) HRESULT, // [43]
        get_CurrentLabeledBy: *const anyopaque, // [44]
        get_CurrentAriaRole: *const anyopaque, // [45]
        get_CurrentAriaProperties: *const anyopaque, // [46]
        get_CurrentIsDataValidForForm: *const anyopaque, // [47]
        get_CurrentControllerFor: *const anyopaque, // [48]
        get_CurrentDescribedBy: *const anyopaque, // [49]
        get_CurrentFlowsTo: *const anyopaque, // [50]
        get_CurrentProviderDescription: *const anyopaque, // [51]
        get_CachedProcessId: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [52]
        get_CachedControlType: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [53]
        get_CachedLocalizedControlType: *const anyopaque, // [54]
        get_CachedName: *const fn (self: *IUIAutomationElement, ret: *?[*]u16) callconv(.winapi) HRESULT, // [55]
        get_CachedAcceleratorKey: *const anyopaque, // [56]
        get_CachedAccessKey: *const anyopaque, // [57]
        get_CachedHasKeyboardFocus: *const anyopaque, // [58]
        get_CachedIsKeyboardFocusable: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [59]
        get_CachedIsEnabled: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [60]
        get_CachedAutomationId: *const fn (self: *IUIAutomationElement, ret: *?[*]u16) callconv(.winapi) HRESULT, // [61]
        get_CachedClassName: *const fn (self: *IUIAutomationElement, ret: *?[*]u16) callconv(.winapi) HRESULT, // [62]
        get_CachedHelpText: *const anyopaque, // [63]
        get_CachedCulture: *const anyopaque, // [64]
        get_CachedIsControlElement: *const anyopaque, // [65]
        get_CachedIsContentElement: *const anyopaque, // [66]
        get_CachedIsPassword: *const fn (self: *IUIAutomationElement, ret: *i32) callconv(.winapi) HRESULT, // [67]
        get_CachedNativeWindowHandle: *const anyopaque, // [68]
        get_CachedItemType: *const anyopaque, // [69]
        get_CachedIsOffscreen: *const anyopaque, // [70]
        get_CachedOrientation: *const anyopaque, // [71]
        get_CachedFrameworkId: *const anyopaque, // [72]
        get_CachedIsRequiredForForm: *const anyopaque, // [73]
        get_CachedItemStatus: *const anyopaque, // [74]
        get_CachedBoundingRectangle: *const fn (self: *IUIAutomationElement, ret: *RECT) callconv(.winapi) HRESULT, // [75]
        get_CachedLabeledBy: *const anyopaque, // [76]
        get_CachedAriaRole: *const anyopaque, // [77]
        get_CachedAriaProperties: *const anyopaque, // [78]
        get_CachedIsDataValidForForm: *const anyopaque, // [79]
        get_CachedControllerFor: *const anyopaque, // [80]
        get_CachedDescribedBy: *const anyopaque, // [81]
        get_CachedFlowsTo: *const anyopaque, // [82]
        get_CachedProviderDescription: *const anyopaque, // [83]
        GetClickablePoint: *const fn (self: *IUIAutomationElement, clickable: *POINT, got: *i32) callconv(.winapi) HRESULT, // [84]
    };
    pub const slot_count = 85;
};

pub const IUIAutomationElementArray = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationElementArray, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationElementArray) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationElementArray) callconv(.winapi) u32, // [2]
        get_Length: *const fn (self: *IUIAutomationElementArray, length: *i32) callconv(.winapi) HRESULT, // [3]
        GetElement: *const fn (self: *IUIAutomationElementArray, index: i32, element: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [4]
    };
    pub const slot_count = 5;
};

pub const IUIAutomationCondition = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationCondition, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationCondition) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationCondition) callconv(.winapi) u32, // [2]
    };
    pub const slot_count = 3;
};

pub const IUIAutomationTreeWalker = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationTreeWalker, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationTreeWalker) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationTreeWalker) callconv(.winapi) u32, // [2]
        GetParentElement: *const anyopaque, // [3]
        GetFirstChildElement: *const fn (self: *IUIAutomationTreeWalker, element: *IUIAutomationElement, first: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [4]
        GetLastChildElement: *const anyopaque, // [5]
        GetNextSiblingElement: *const fn (self: *IUIAutomationTreeWalker, element: *IUIAutomationElement, next: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [6]
        GetPreviousSiblingElement: *const anyopaque, // [7]
        NormalizeElement: *const anyopaque, // [8]
        GetParentElementBuildCache: *const fn (self: *IUIAutomationTreeWalker, element: *IUIAutomationElement, req: *IUIAutomationCacheRequest, parent: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [9]
        GetFirstChildElementBuildCache: *const fn (self: *IUIAutomationTreeWalker, element: *IUIAutomationElement, req: *IUIAutomationCacheRequest, first: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [10]
        GetLastChildElementBuildCache: *const anyopaque, // [11]
        GetNextSiblingElementBuildCache: *const fn (self: *IUIAutomationTreeWalker, element: *IUIAutomationElement, req: *IUIAutomationCacheRequest, next: *?*IUIAutomationElement) callconv(.winapi) HRESULT, // [12]
        GetPreviousSiblingElementBuildCache: *const anyopaque, // [13]
        NormalizeElementBuildCache: *const anyopaque, // [14]
        get_Condition: *const anyopaque, // [15]
    };
    pub const slot_count = 16;
};

pub const IUIAutomationCacheRequest = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationCacheRequest, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationCacheRequest) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationCacheRequest) callconv(.winapi) u32, // [2]
        AddProperty: *const fn (self: *IUIAutomationCacheRequest, property_id: i32) callconv(.winapi) HRESULT, // [3]
        AddPattern: *const anyopaque, // [4]
        Clone: *const anyopaque, // [5]
        get_TreeScope: *const anyopaque, // [6]
        put_TreeScope: *const fn (self: *IUIAutomationCacheRequest, scope: i32) callconv(.winapi) HRESULT, // [7]
        get_TreeFilter: *const anyopaque, // [8]
        put_TreeFilter: *const fn (self: *IUIAutomationCacheRequest, filter: *IUIAutomationCondition) callconv(.winapi) HRESULT, // [9]
        get_AutomationElementMode: *const anyopaque, // [10]
        put_AutomationElementMode: *const anyopaque, // [11]
    };
    pub const slot_count = 12;
};

pub const IUIAutomationInvokePattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationInvokePattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationInvokePattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationInvokePattern) callconv(.winapi) u32, // [2]
        Invoke: *const fn (self: *IUIAutomationInvokePattern) callconv(.winapi) HRESULT, // [3]
    };
    pub const slot_count = 4;
};

pub const IUIAutomationValuePattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationValuePattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationValuePattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationValuePattern) callconv(.winapi) u32, // [2]
        SetValue: *const fn (self: *IUIAutomationValuePattern, value: ?[*]u16) callconv(.winapi) HRESULT, // [3]
        get_CurrentValue: *const fn (self: *IUIAutomationValuePattern, ret: *?[*]u16) callconv(.winapi) HRESULT, // [4]
        get_CurrentIsReadOnly: *const fn (self: *IUIAutomationValuePattern, ret: *i32) callconv(.winapi) HRESULT, // [5]
        get_CachedValue: *const anyopaque, // [6]
        get_CachedIsReadOnly: *const anyopaque, // [7]
    };
    pub const slot_count = 8;
};

pub const IUIAutomationSelectionItemPattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationSelectionItemPattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationSelectionItemPattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationSelectionItemPattern) callconv(.winapi) u32, // [2]
        Select: *const fn (self: *IUIAutomationSelectionItemPattern) callconv(.winapi) HRESULT, // [3]
        AddToSelection: *const anyopaque, // [4]
        RemoveFromSelection: *const anyopaque, // [5]
        get_CurrentIsSelected: *const anyopaque, // [6]
        get_CurrentSelectionContainer: *const anyopaque, // [7]
        get_CachedIsSelected: *const anyopaque, // [8]
        get_CachedSelectionContainer: *const anyopaque, // [9]
    };
    pub const slot_count = 10;
};

pub const IUIAutomationExpandCollapsePattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationExpandCollapsePattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationExpandCollapsePattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationExpandCollapsePattern) callconv(.winapi) u32, // [2]
        Expand: *const fn (self: *IUIAutomationExpandCollapsePattern) callconv(.winapi) HRESULT, // [3]
        Collapse: *const anyopaque, // [4]
        get_CurrentExpandCollapseState: *const anyopaque, // [5]
        get_CachedExpandCollapseState: *const anyopaque, // [6]
    };
    pub const slot_count = 7;
};

pub const IUIAutomationScrollItemPattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationScrollItemPattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationScrollItemPattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationScrollItemPattern) callconv(.winapi) u32, // [2]
        ScrollIntoView: *const fn (self: *IUIAutomationScrollItemPattern) callconv(.winapi) HRESULT, // [3]
    };
    pub const slot_count = 4;
};

pub const IUIAutomationScrollPattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationScrollPattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationScrollPattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationScrollPattern) callconv(.winapi) u32, // [2]
        Scroll: *const fn (self: *IUIAutomationScrollPattern, horizontal: i32, vertical: i32) callconv(.winapi) HRESULT, // [3]
        SetScrollPercent: *const anyopaque, // [4]
        get_CurrentHorizontalScrollPercent: *const anyopaque, // [5]
        get_CurrentVerticalScrollPercent: *const anyopaque, // [6]
        get_CurrentHorizontalViewSize: *const anyopaque, // [7]
        get_CurrentVerticalViewSize: *const anyopaque, // [8]
        get_CurrentHorizontallyScrollable: *const anyopaque, // [9]
        get_CurrentVerticallyScrollable: *const anyopaque, // [10]
        get_CachedHorizontalScrollPercent: *const anyopaque, // [11]
        get_CachedVerticalScrollPercent: *const anyopaque, // [12]
        get_CachedHorizontalViewSize: *const anyopaque, // [13]
        get_CachedVerticalViewSize: *const anyopaque, // [14]
        get_CachedHorizontallyScrollable: *const anyopaque, // [15]
        get_CachedVerticallyScrollable: *const anyopaque, // [16]
    };
    pub const slot_count = 17;
};

pub const IUIAutomationTextPattern = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationTextPattern, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationTextPattern) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationTextPattern) callconv(.winapi) u32, // [2]
        RangeFromPoint: *const anyopaque, // [3]
        RangeFromChild: *const anyopaque, // [4]
        GetSelection: *const anyopaque, // [5]
        GetVisibleRanges: *const anyopaque, // [6]
        get_DocumentRange: *const fn (self: *IUIAutomationTextPattern, range: *?*IUIAutomationTextRange) callconv(.winapi) HRESULT, // [7]
        get_SupportedTextSelection: *const anyopaque, // [8]
    };
    pub const slot_count = 9;
};

pub const IUIAutomationTextRange = extern struct {
    vtbl: *const Vtbl,
    pub const Vtbl = extern struct {
        QueryInterface: *const fn (self: *IUIAutomationTextRange, riid: *const GUID, out: *?*anyopaque) callconv(.winapi) HRESULT, // [0]
        AddRef: *const fn (self: *IUIAutomationTextRange) callconv(.winapi) u32, // [1]
        Release: *const fn (self: *IUIAutomationTextRange) callconv(.winapi) u32, // [2]
        Clone: *const anyopaque, // [3]
        Compare: *const anyopaque, // [4]
        CompareEndpoints: *const anyopaque, // [5]
        ExpandToEnclosingUnit: *const anyopaque, // [6]
        FindAttribute: *const anyopaque, // [7]
        FindText: *const anyopaque, // [8]
        GetAttributeValue: *const anyopaque, // [9]
        GetBoundingRectangles: *const anyopaque, // [10]
        GetEnclosingElement: *const anyopaque, // [11]
        GetText: *const fn (self: *IUIAutomationTextRange, max_length: i32, ret: *?[*]u16) callconv(.winapi) HRESULT, // [12]
        Move: *const anyopaque, // [13]
        MoveEndpointByUnit: *const anyopaque, // [14]
        MoveEndpointByRange: *const anyopaque, // [15]
        Select: *const anyopaque, // [16]
        AddToSelection: *const anyopaque, // [17]
        RemoveFromSelection: *const anyopaque, // [18]
        ScrollIntoView: *const anyopaque, // [19]
        GetChildren: *const anyopaque, // [20]
    };
    pub const slot_count = 21;
};

comptime {
    std.debug.assert(@sizeOf(IUIAutomation.Vtbl) == 58 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomation2.Vtbl) == 64 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationElement.Vtbl) == 85 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationElementArray.Vtbl) == 5 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationCondition.Vtbl) == 3 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationTreeWalker.Vtbl) == 16 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationCacheRequest.Vtbl) == 12 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationInvokePattern.Vtbl) == 4 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationValuePattern.Vtbl) == 8 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationSelectionItemPattern.Vtbl) == 10 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationExpandCollapsePattern.Vtbl) == 7 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationScrollItemPattern.Vtbl) == 4 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationScrollPattern.Vtbl) == 17 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationTextPattern.Vtbl) == 9 * @sizeOf(usize));
    std.debug.assert(@sizeOf(IUIAutomationTextRange.Vtbl) == 21 * @sizeOf(usize));
}

comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "ElementFromHandle") == 6 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "get_ControlViewWalker") == 14 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "GetRootElement") == 5 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentName") == 23 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentClassName") == 30 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentControlType") == 21 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentIsEnabled") == 28 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentIsKeyboardFocusable") == 27 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentIsPassword") == 35 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentProcessId") == 20 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentBoundingRectangle") == 43 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "CreateCacheRequest") == 20 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "ElementFromHandleBuildCache") == 10 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationCacheRequest.Vtbl, "AddProperty") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTreeWalker.Vtbl, "GetFirstChildElementBuildCache") == 10 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTreeWalker.Vtbl, "GetNextSiblingElementBuildCache") == 12 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedName") == 55 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedControlType") == 53 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedIsEnabled") == 60 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedIsKeyboardFocusable") == 59 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedIsPassword") == 67 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedBoundingRectangle") == 75 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElementArray.Vtbl, "get_Length") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElementArray.Vtbl, "GetElement") == 4 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTreeWalker.Vtbl, "GetFirstChildElement") == 4 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTreeWalker.Vtbl, "GetNextSiblingElement") == 6 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationInvokePattern.Vtbl, "Invoke") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationValuePattern.Vtbl, "get_CurrentValue") == 4 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationValuePattern.Vtbl, "get_CurrentIsReadOnly") == 5 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "CreatePropertyCondition") == 23 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "CreateAndCondition") == 25 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "CreateOrCondition") == 28 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "get_ControlViewCondition") == 18 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "GetFocusedElementBuildCache") == 12 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "FindFirstBuildCache") == 7 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "FindAllBuildCache") == 8 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "BuildUpdatedCache") == 9 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "GetCachedPropertyValue") == 12 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "GetCurrentPropertyValue") == 10 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "GetCachedChildren") == 19 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedProcessId") == 52 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationCacheRequest.Vtbl, "put_TreeScope") == 7 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationCacheRequest.Vtbl, "put_TreeFilter") == 9 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation2.Vtbl, "put_ConnectionTimeout") == 61 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation2.Vtbl, "put_TransactionTimeout") == 63 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation2.Vtbl, "get_ConnectionTimeout") == 60 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation2.Vtbl, "get_TransactionTimeout") == 62 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "SetFocus") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "GetCurrentPattern") == 16 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "GetClickablePoint") == 84 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CurrentHasKeyboardFocus") == 26 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomation.Vtbl, "ElementFromPointBuildCache") == 11 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTreeWalker.Vtbl, "GetParentElementBuildCache") == 9 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationValuePattern.Vtbl, "SetValue") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationSelectionItemPattern.Vtbl, "Select") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationExpandCollapsePattern.Vtbl, "Expand") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationScrollItemPattern.Vtbl, "ScrollIntoView") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationScrollPattern.Vtbl, "Scroll") == 3 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedAutomationId") == 61 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationElement.Vtbl, "get_CachedClassName") == 62 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTextPattern.Vtbl, "get_DocumentRange") == 7 * @sizeOf(usize)); }
comptime { std.debug.assert(@offsetOf(IUIAutomationTextRange.Vtbl, "GetText") == 12 * @sizeOf(usize)); }
